# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

puts 'Conjuring ingredients'

Ingredient.create(name: 'Lemon')
Ingredient.create(name: 'Ice')
Ingredient.create(name: 'Mint leaves')

Ingredient.create(name: 'Ginger')
Ingredient.create(name: 'Cloves')
Ingredient.create(name: 'Ale')
Ingredient.create(name: 'Nutmeg')
Ingredient.create(name: 'Brown sugar')
Ingredient.create(name: 'Egg yolk(s)')
Ingredient.create(name: 'Butter')

Ingredient.create(name: 'Egg white(s)')
Ingredient.create(name: 'Egg(s)')
Ingredient.create(name: 'Light rum')
Ingredient.create(name: 'Applejack')
Ingredient.create(name: 'Gin')
Ingredient.create(name: 'Dark rum')
Ingredient.create(name: 'Sweet Vermouth')
Ingredient.create(name: 'Dry Vermouth')
Ingredient.create(name: 'Strawberry schnapps')
Ingredient.create(name: 'Scotch')
Ingredient.create(name: 'Apricot brandy')
Ingredient.create(name: 'Triple sec')
Ingredient.create(name: 'Southern Comfort')
Ingredient.create(name: 'Orange bitters')
Ingredient.create(name: 'Brandy')
Ingredient.create(name: 'Lemon vodka')
Ingredient.create(name: 'Blended whiskey')
Ingredient.create(name: 'Amaretto')
Ingredient.create(name: 'Tea')
Ingredient.create(name: 'Champagne')
Ingredient.create(name: 'Coffee liquer')
Ingredient.create(name: 'Bourbon')
Ingredient.create(name: 'Licor 43')
Ingredient.create(name: 'Tequila')
Ingredient.create(name: 'Vodka')
Ingredient.create(name: 'Añjo rum')
Ingredient.create(name: 'Bitters')
Ingredient.create(name: 'Sugar')
Ingredient.create(name: 'Kahlua')
Ingredient.create(name: 'Demerara Sugar')
Ingredient.create(name: 'Dubonnet Rouge')
Ingredient.create(name: 'Red Wine')
Ingredient.create(name: 'Dry White wine')
Ingredient.create(name: 'Sweet White wine')
Ingredient.create(name: 'Rosé')
Ingredient.create(name: 'Watermelon')
Ingredient.create(name: 'Cantaloupe')
Ingredient.create(name: 'Lime juice')
Ingredient.create(name: 'Lemon juice')
Ingredient.create(name: 'Lime')
Ingredient.create(name: 'Irish Whiskey')
Ingredient.create(name: 'Apple brandy')
Ingredient.create(name: 'Carbonated water')
Ingredient.create(name: 'Coca Cola')
Ingredient.create(name: 'Cherry brandy')
Ingredient.create(name: 'Creme de Cacao')
Ingredient.create(name: 'Grenadine')
Ingredient.create(name: 'Port')
Ingredient.create(name: 'Coffee brandy')
Ingredient.create(name: 'Rum')
Ingredient.create(name: 'Grapefruit juice')
Ingredient.create(name: 'Ricard')
Ingredient.create(name: 'Sherry')
Ingredient.create(name: 'Cognac')
Ingredient.create(name: 'Sloe gin')
Ingredient.create(name: 'Apple juice')
Ingredient.create(name: 'Pineapple juice')
Ingredient.create(name: 'Sugar syrup')
Ingredient.create(name: 'Milk')
Ingredient.create(name: 'Strawberries')
Ingredient.create(name: 'Chocolate syrup')
Ingredient.create(name: 'Yoghurt')
Ingredient.create(name: 'Mango')
Ingredient.create(name: 'Berries')
Ingredient.create(name: 'Grapes')
Ingredient.create(name: 'Kiwi')
Ingredient.create(name: 'Tomato juice')
Ingredient.create(name: 'Cocoa powder')
Ingredient.create(name: 'Dark chocolate')
Ingredient.create(name: 'Milk chocolate')
Ingredient.create(name: 'White chocolate')
Ingredient.create(name: 'Heavy cream')
Ingredient.create(name: 'Whipped cream')
Ingredient.create(name: 'Sour Cream')
Ingredient.create(name: 'Galliano')
Ingredient.create(name: 'Peach Vodka')
Ingredient.create(name: 'Ouzo')
Ingredient.create(name: 'Coffee')
Ingredient.create(name: 'Spiced rum')
Ingredient.create(name: 'Water')
Ingredient.create(name: 'Espresso')
Ingredient.create(name: 'Angelica root')
Ingredient.create(name: 'Orange')
Ingredient.create(name: 'Cranberries')
Ingredient.create(name: 'Johnnie Walker')
Ingredient.create(name: 'Apple cider')
Ingredient.create(name: 'Everclear')
Ingredient.create(name: 'Cranberry juice')
Ingredient.create(name: 'Grape juice')
Ingredient.create(name: 'Peach nectar')
Ingredient.create(name: 'Firewater')
Ingredient.create(name: 'Lager')
Ingredient.create(name: 'Whiskey')
Ingredient.create(name: 'Absolut Citron')
Ingredient.create(name: 'Pisco')
Ingredient.create(name: 'Irish cream')
Ingredient.create(name: 'Chocolate liquer')
Ingredient.create(name: 'Midori melon liquer')
Ingredient.create(name: 'Sake')
Ingredient.create(name: 'Matcha')
Ingredient.create(name: 'Sambuca')
Ingredient.create(name: 'Cider')
Ingredient.create(name: 'Sprite')
Ingredient.create(name: '7-Up')
Ingredient.create(name: 'Fanta')
Ingredient.create(name: 'Cassis')
Ingredient.create(name: 'Blackberry brandy')
Ingredient.create(name: 'Peppermint schnapps')
Ingredient.create(name: 'Creme de Cassis')
Ingredient.create(name: 'Baileys')

puts 'All done!'
